# ~/ros2_ws/src/tortoisebot_ros2_docker/docker-compose.yml

version: "3.7"

services:
  gazebo:
    container_name: tortoisebot-ros2-gazebo
    image: eldgar/tortoisebot-ros2-docker-gazebo:updated
    command: >
      bash -c "source /opt/ros/galactic/setup.bash &&
               source install/setup.bash &&
               ros2 launch tortoisebot_bringup bringup.launch.py use_sim_time:=True"
    # Set up X11 for GUI
    environment:
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  waypoints:
    container_name: tortoisebot-ros2-waypoints
    image: eldgar/tortoisebot-ros2-docker-waypoints:latest
    depends_on:
      - gazebo
    command: >
      bash -c "source /opt/ros/galactic/setup.bash &&
               source install/setup.bash &&
               ros2 run tortoisebot_waypoints tortoisebot_action_server"
  
  test:
    container_name: tortoisebot-ros2-test
    image: eldgar/tortoisebot-ros2-waypoints-test:latest
    depends_on:
      - waypoints
    command: >
      bash -c "source /opt/ros/galactic/setup.bash &&
               source install/setup.bash &&
               colcon test --packages-select tortoisebot_waypoints --event-handler=console_direct+ && \
               colcon test-result --all && \
               sleep 65"