pipeline {
    agent any
    stages {
        stage('Launch Simulation with Docker Compose') {
            steps {
                sh '''
                echo "Stopping any existing containers..."
                sudo docker-compose -f ~/ros2_ws/src/docker-compose.yml down || true

                echo "Starting Docker Compose..."
                sudo docker-compose -f ~/ros2_ws/src/docker-compose.yml up -d
                echo "Waiting for ROS2 containers to initialize..."
                sleep 85
                '''
            }
        }
        stage('Check Gazebo Logs') {
            steps {
                sh '''
                echo "Fetching logs from test container..."
                sudo docker logs tortoisebot-ros2-waypoints
                '''
            }
        }
        stage('Fetch Test Logs') {
            steps {
                sh '''
                echo "Fetching logs from test container..."
                sudo docker logs tortoisebot-ros2-test
                '''
            }
        }
        stage('Cleanup') {
            steps {
                sh '''
                echo "Stopping and removing Docker containers..."
                sudo docker-compose -f ~/ros2_ws/src/docker-compose.yml down
                echo "Cleanup complete."
                '''
            }
        }
    }
    triggers {
        pollSCM('H/3 * * * *') // Poll the repository every 3 minutes
    }
}












